<a href="https://colab.research.google.com/github/Vasavi430/Cursor/blob/main/Day%203%20code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install opendatasets

Requirement already satisfied: opendatasets in /usr/local/lib/python3.10/dist-packages (0.1.22)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from opendatasets) (4.66.6)
Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from opendatasets) (8.1.7)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2024.8.30)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.10)

In [3]:
import opendatasets as od

In [4]:
od.download("https://www.kaggle.com/datasets/mjlyma/customer-purchase-dataset")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: vasavisuthapalli
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/mjlyma/customer-purchase-dataset
Downloading customer-purchase-dataset.zip to ./customer-purchase-dataset

100%|██████████| 38.3k/38.3k [00:00<00:00, 41.8MB/s]

In [5]:
import pandas as pd
data = pd.read_csv('/content/customer-purchase-dataset/Customer Purchase Data.csv')

In [6]:
data.head()

,Number,Age,Income,Spending_Score,Membership_Years,Purchase_Frequency,Last_Purchase_Amount
0,1,56,61350.84215,12372.864450,15,77.685590,6232.122440
1,2,46,53777.18224,11001.604230,10,51.858351,5545.849698
2,3,32,39460.32263,8007.385018,19,98.166371,4054.645293
3,4,60,66672.12210,13526.548370,12,62.530976,6815.544393
4,5,38,44459.08553,9059.304083,9,46.470533,4617.833484

In [8]:
mport pandas as pd
import statistics
from scipy.stats import skew

# Creating the dataset
data = {
    "Number": [1, 2, 3, 4, 5],
    "Age": [56, 46, 32, 60, 38],
    "Income": [61350.84215, 53777.18224, 39460.32263, 66672.12210, 44459.08553],
    "Spending_Score": [12372.86445, 11001.60423, 8007.385018, 13526.54837, 9059.304083],
    "Membership_Years": [15, 10, 19, 12, 9],
    "Purchase_Frequency": [77.685590, 51.858351, 98.166371, 62.530976, 46.470533],
    "Last_Purchase_Amount": [6232.12244, 5545.849698, 4054.645293, 6815.544393, 4617.833484]
}

# Convert the data to a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print("Dataset:")i
print(df)

# Calculations
def calculate_statistics(column_name):
    col_data = df[column_name]
    mean_value = statistics.mean(col_data)
    median_value = statistics.median(col_data)
    try:
        mode_value = statistics.mode(col_data)
    except statistics.StatisticsError:
        mode_value = "No mode (all values unique)"
    range_value = max(col_data) - min(col_data)
    skewness_value = skew(col_data)

    return {
        "Mean": mean_value,
        "Median": median_value,
        "Mode": mode_value,
        "Range": range_value,
        "Skewness": skewness_value
    }

# Choose columns for analysis
columns_to_analyze = ["Age", "Income", "Spending_Score", "Membership_Years", "Purchase_Frequency", "Last_Purchase_Amount"]

# Compute and display results
print("\nStatistics:")
for column in columns_to_analyze:
    stats = calculate_statistics(column)
    print(f"{column}: {stats}")

Dataset:
   Number  Age       Income  Spending_Score  Membership_Years  \
0       1   56  61350.84215    12372.864450                15
1       2   46  53777.18224    11001.604230                10
2       3   32  39460.32263     8007.385018                19
3       4   60  66672.12210    13526.548370                12
4       5   38  44459.08553     9059.304083                 9

   Purchase_Frequency  Last_Purchase_Amount
0           77.685590           6232.122440
1           51.858351           5545.849698
2           98.166371           4054.645293
3           62.530976           6815.544393
4           46.470533           4617.833484

Statistics:
Age: {'Mean': 46.4, 'Median': 46, 'Mode': 56, 'Range': 28, 'Skewness': -0.03052073536344534}
Income: {'Mean': 53143.91093, 'Median': 53777.18224, 'Mode': 61350.84215, 'Range': 27211.79946999999, 'Skewness': -0.03619806972003976}
Spending_Score: {'Mean': 10793.5412302, 'Median': 11001.60423, 'Mode': 12372.86445, 'Range': 5519.1633520000005, 'Skewness': -0.05859855695001086}
Membership_Years: {'Mean': 13, 'Median': 12, 'Mode': 15, 'Range': 10, 'Skewness': 0.5504818825631803}
Purchase_Frequency: {'Mean': 67.3423642, 'Median': 62.530976, 'Mode': 77.68559, 'Range': 51.695837999999995, 'Skewness': 0.5312445329317648}
Last_Purchase_Amount: {'Mean': 5453.1990616, 'Median': 5545.849698, 'Mode': 6232.12244, 'Range': 2760.8991, 'Skewness': -0.061011487816856}

In [9]:
import pandas as pd
import statistics
from scipy.stats import skew

# Creating the dataset
data = {
    "Number": [1, 2, 3, 4, 5],
    "Age": [56, 46, 32, 60, 38],
    "Income": [61350.84215, 53777.18224, 39460.32263, 66672.12210, 44459.08553],
    "Spending_Score": [12372.86445, 11001.60423, 8007.385018, 13526.54837, 9059.304083],
    "Membership_Years": [15, 10, 19, 12, 9],
    "Purchase_Frequency": [77.685590, 51.858351, 98.166371, 62.530976, 46.470533],
    "Last_Purchase_Amount": [6232.12244, 5545.849698, 4054.645293, 6815.544393, 4617.833484],
    "Category": ["Gold", "Silver", "Gold", "Platinum", "Silver"],  # Nominal Data
    "Satisfaction_Level": [3, 2, 5, 4, 1],  # Ordinal Data
}

# Convert the data to a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print("Dataset:")
print(df)

# Calculations
def calculate_statistics(column_name):
    col_data = df[column_name]
    mean_value = statistics.mean(col_data)
    median_value = statistics.median(col_data)
    try:
        mode_value = statistics.mode(col_data)
    except statistics.StatisticsError:
        mode_value = "No mode (all values unique)"
    range_value = max(col_data) - min(col_data)
    skewness_value = skew(col_data)
    variance_value = statistics.variance(col_data)
    std_deviation = statistics.stdev(col_data)

    # Detect outliers using 1.5 * IQR rule
    q1 = col_data.quantile(0.25) if hasattr(col_data, "quantile") else None
    q3 = col_data.quantile(0.75) if hasattr(col_data, "quantile") else None
    iqr = q3 - q1 if q1 is not None and q3 is not None else None
    outliers = col_data[(col_data < (q1 - 1.5 * iqr)) | (col_data > (q3 + 1.5 * iqr))] if iqr else []

    return {
        "Mean": mean_value,
        "Median": median_value,
        "Mode": mode_value,
        "Range": range_value,
        "Skewness": skewness_value,
        "Variance": variance_value,
        "Standard Deviation": std_deviation,
        "Outliers": list(outliers) if len(outliers) > 0 else "No outliers"
    }

# Display nominal and ordinal data
print("\nNominal Data (Categories):")
print(df["Category"].unique())

print("\nOrdinal Data (Satisfaction Levels):")
print(sorted(df["Satisfaction_Level"].unique()))

# Choose numerical columns for analysis
columns_to_analyze = ["Age", "Income", "Spending_Score", "Membership_Years", "Purchase_Frequency", "Last_Purchase_Amount"]

# Compute and display results
print("\nStatistics:")
for column in columns_to_analyze:
    stats = calculate_statistics(column)
    print(f"{column}: {stats}")

Dataset:
   Number  Age       Income  Spending_Score  Membership_Years  \
0       1   56  61350.84215    12372.864450                15
1       2   46  53777.18224    11001.604230                10
2       3   32  39460.32263     8007.385018                19
3       4   60  66672.12210    13526.548370                12
4       5   38  44459.08553     9059.304083                 9

   Purchase_Frequency  Last_Purchase_Amount  Category  Satisfaction_Level
0           77.685590           6232.122440      Gold                   3
1           51.858351           5545.849698    Silver                   2
2           98.166371           4054.645293      Gold                   5
3           62.530976           6815.544393  Platinum                   4
4           46.470533           4617.833484    Silver                   1

Nominal Data (Categories):
['Gold' 'Silver' 'Platinum']

Ordinal Data (Satisfaction Levels):
[1, 2, 3, 4, 5]

Statistics:
Age: {'Mean': 46.4, 'Median': 46, 'Mode': 56, 'Range': 28, 'Skewness': -0.03052073536344534, 'Variance': 138.8, 'Standard Deviation': 11.781341180018513, 'Outliers': 'No outliers'}
Income: {'Mean': 53143.91093, 'Median': 53777.18224, 'Mode': 61350.84215, 'Range': 27211.79946999999, 'Skewness': -0.03619806972003976, 'Variance': 128358507.7635936, 'Standard Deviation': 11329.541374812734, 'Outliers': 'No outliers'}
Spending_Score: {'Mean': 10793.5412302, 'Median': 11001.60423, 'Mode': 12372.86445, 'Range': 5519.1633520000005, 'Skewness': -0.05859855695001086, 'Variance': 5194281.248048008, 'Standard Deviation': 2279.096585941019, 'Outliers': 'No outliers'}
Membership_Years: {'Mean': 13, 'Median': 12, 'Mode': 15, 'Range': 10, 'Skewness': 0.5504818825631803, 'Variance': 16.5, 'Standard Deviation': 4.06201920231798, 'Outliers': 'No outliers'}
Purchase_Frequency: {'Mean': 67.3423642, 'Median': 62.530976, 'Mode': 77.68559, 'Range': 51.695837999999995, 'Skewness': 0.5312445329317648, 'Variance': 438.90979349659966, 'Standard Deviation': 20.95017406840811, 'Outliers': 'No outliers'}
Last_Purchase_Amount: {'Mean': 5453.1990616, 'Median': 5545.849698, 'Mode': 6232.12244, 'Range': 2760.8991, 'Skewness': -0.061011487816856, 'Variance': 1281269.7159337539, 'Standard Deviation': 1131.9318512762832, 'Outliers': 'No outliers'}